namespace: cisco
name: mso
version: 0.0.2
authors:
- Dag Wieers (@dagwieers) <dag@wieers.com>

description: An Ansible collection for managing Cisco ACI Multi-Site
license: GPL-3.0-or-later
tags:
- aci
- cisco
- cloud
- collection
- mso
- multisite
- networking
- sdn
dependencies: {}

repository: https://github.com/datacenter/ansible-mso
documentation: https://docs.ansible.com/ansible/latest/scenario_guides/guide_aci.html
homepage: https://github.com/datacenter/ansible-mso/wiki
issues: https://github.com/datacenter/ansible-mso/issues
readme: README.md
